---
locale: "en-US"
title: adfinis/docs
email: support@adfinis.com
description: >-
  üìöÔ∏è Docs for Adfinis projects
baseurl: "/adfinis.github.io/"
url: "https://docs.adfinis.com"

header:
  button:
    title: "Contact"
    href: "https://adfinis.com/en/contact/"

hero:
  image_url: "docs/images/PeopleatAdfinis.jpg"

footer:
  blog:
    name: "Blog"
    href: "https://adfinis.com/blog/"
  privacy:
    name: "Privacy policy"
    href: "https://adfinis.com/en/privacypolicy/"
  linkedin:
    href: "https://www.linkedin.com/company/adfinis-com"
  github:
    href: "https://github.com/adfinis/"

remote_theme: Maryana-B/jekyll-theme-adfinis-ng
